# Site settings
title: XVI | Wargame early 16th Polish army
description: "Blog about painting and modeling miniatures, mostly for my 16th century Polish army."
url: "http://0xddr.github.io/xvi/"
author:
  name: "Jan Łukaszewicz"
  email: "janek99+xvi@gmail.com"
  url: "http://0xddr.github.io/xvi/"

# Build settings
baseurl: /xvi/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

images_dir: /xvi/assets/images/

